language: node_js
node_js:
- '4'
branches:
  only:
  - master
 before_install:
- export TZ='Asia/Malaysia'
- npm install -g hexo
- npm install -g hexo-cli
# S: Build Lifecycle
install:
- npm install

before_script:
- npm install -g gulp

script:
- gulp dist

after_script:
- cd ./public
- git init
- git config user.name "kenjilee"
- git config user.email "kenjilee81460@yahoo.com"
- git add .
- git commit -m "Update docs"
- git push -f "https://${GH_TOKEN}@${github.com/kenjilee/kenjilee.github.io.git}" master:gh-pages
# E: Build LifeCycle

env:
  global:
     - GH_REF: github.com/kenjilee/kenjilee.github.io.git
     - secure: "0RsJqcwn5h6nmjUXTDK8b0WFrsnPKgiuoiNTrlT7zfqE5E9F8gL4TMvSFf7LG10nQH9/uWditljHKsxBSMYi00+cGnvxxiNXF3Hvjx1vYG0u4jqoYRVn6e/6s4qfLNSGMa8IySTLtt5UTWDOtRxEwJsnXT1Z1euEyCCHE1E1F7dvkHxT/oM/F6lIcClnu0EZ4G1L4RiXuzGUU/Pfo6rXiUZJeWJyz6O++B6RHkwgueKDi4Uge8XSoSTL9o0O+xJv00v84K8e1eNrxmydwPtDKQmCnyefzX+BKgHMrOLPtpqJb+qr6Y7XrE/NyIXHmWREBSTTtORE+vvlr1bz/MU51Q2bjbVzYwzB2/bfk97sYvU4GUWpf9YS8lnfj5zULPNqdaxAcznDYDe0oHzy2fhPsUNmB9yKNIAieFIbj+YmuVgqzHmDwRmncSclDAyDOuMRip14+ia6airdcujv5qDeI/Ih7hb2C48zszOLlzJd8RO/7Hz2RKcXluWbvv9tyzU5wRdvSLmWM8eoq5lQ/NQaeo97vvfhnpE2qWT9EWB9cR2kPFWU9mmFkMfEv/FODxjF+nhLhdo3YaztruC1XUmDtmuf9f8agNZKMytN9YXQYtU2CZ1LxuPGJ4hcguFtIR0qUDp53pY20G3JjskH33KDLpwjwqzo/vGLSJ6vZX4UUVc="
 