language: node_js
node_js:
- '4'
branches:
  only:
  - dev
env:
  global:
     - GH_REF: github.com/kenjilee/kenjilee.github.io.git
     - secure: "GK2SkmeiGKK5RLNTAx5ncbp6Z3neslLczZ3+jmmZnJ94nPMXle8/BhLvYYIfBwooSHvUR/UqmPHrpwiyhIUqTHKyv3t8zspQmM25ZnarX6B1bPeudcB7gROsvwVQk1JDGti/QVEivcsnNnGULdkPdd3Y1NNC+1B9NdCT5VgY1s3tDnv6ycjkMuc9yZ5oBsC7Gb9OBz2u4XaudwkSYdrnI9aEcInOqinx8Ncw0rilLFntf06a/YX/WG1hBb1ZjCZCtIBNEvdHAfKSQdrrtQLefJectCKIAoLSy5JMm4HY46dysN/2j62dGsMn+wjN6M2D3HroeCKbun/ZKDD/PFgiQ2DC1V28EjG4vA/cx78AbhDkR8vjN77LJUK2G8I7WqrwNNKtUtgZqhsQxBKwmLzYfMOc2CTYS4fVVso57gUZZMqmFg+C++GdljI3UF9+KPkwK2u2LgBZbzBQqrTj9Pn+TZBo15rWAiOGDOCXShGh1UQeIsrjSCsFrmiEaSsQA5DjSumR/pGH59ldXE7BaWDVTa7Sww14/Nj10X9cugTWfPaikCKAFmKJW57N3LSlrIeAaZoimVFrZdzCVrIMsA+xO/Wm//U8fiBIb0jf9+9WbV6SzJ401yaXaqr95vOMRhqfTpXu/SklbKazA+wu1CvA53R1YEn8u3Xy1UK8JSMUAWk="
 before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "kenjilee"
- git config --global user.email kenjilee81460@yahoo.com
- sed -i'' "s~git@github.com:kenjilee/kenjilee.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/kenjilee/kenjilee.github.io.git~"
  _config.yml
# S: Build Lifecycle
install:
- npm install

before_script:
- npm install -g gulp

script:
- gulp dist

after_script:
- cd dist
- git init
- git config user.name "kenjilee"
- git config user.email "kenjilee81460@yahoo.com"
- git add .
- git commit -m "Update docs"
- git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle
