language: node_js
node_js:
- '4'
branches:
  only:
  - dev
env:
  global:
  - secure: 4jGM8lOj7/Ow95Jh4mL3OoaYHuaQ8iqy+S6AGlVZbGD6Us6BX7j5TWi+y8PxUa+hGuhikch6OFDv1hNPMNI3WkssbQ1rbbuonM7spvAN8Jp6bfNi/bZiHFfvQGmfR5tvAGMAHeiay/Tw09SDiX8q45frxUmr8p2JWwfqc4D6jKFdN6os3Ho7rxQlT65kKlNhc9FfuHvG3Cwmfj59cHyBXSd6ni/3ZFJjM2PSfdPy6NO74lPIBrIzguPJkbtcEbfk9+NI83U9WNv+ZSdvQde+47m9l2LvvUAkcdd9Y9xcid7jsDFJ7mp1sGEFRbQG1SXsfh5dm6MW0TPa1GHmpSOowctIfnzuwq1vUeU6dL5Mcp+4rXl19XD+wfT2ta/Vc80qpoo12D5pyWZQ47zzdva/CBgBYEv6JVHV+2bgt/XqYaQJfWWzUo8EtHYux/Dl/d4Z2mO0ST20IfLsKuibnHpeQrdYy7N8UI6DH2g/Z54WKJjrN76Ul+/XkE/yPLxdiJj6SX/nLDkaX46I2vAMX5LVtfwxYANniylQaRgEY2A5sgCO738JeOfB0laOw0PAc+Xsjb5QTE/h8rr81NzlJ2Z7XJHk84V5XEmIlLLwowNwe/x2t4XeufYbZCS7dCYddeCcwvlLf0TzsqTUlpN0RVCwrbqHGMXaYEg9c6TNS7UZF1I=
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
- git config --global user.name "kenjilee"
- git config --global user.email kenjilee81460@yahoo.com
- sed -i'' "s~git@github.com:kenjilee/kenjilee.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/kenjilee/kenjilee.github.io.git~"
  _config.yml
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
- hexo deploy
